/**
 * 金融 / 支付相关词条（订单、交易、对账、发票、凭证等）
 *
 * 自动拆分自原 dictBusiness.ts（2026-06-25）
 * 同 key 重复会 TS 编译报错，修改时请先确认该字未在其它分区登记。
 */
const dict: Record<string, string> = {
  // ============ 金融 / 支付 ============
  银行: "bank",
  银行账户: "bankAccount",
  银行账号: "bankAccount",
  银行流水: "bankStatement",
  银行回单: "bankReceipt",
  银行回执: "bankReceipt",
  银行卡: "bankCard",
  信用卡: "creditCard",
  借记卡: "debitCard",
  储蓄卡: "debitCard",
  礼品卡: "giftCard",
  储值卡: "storedCard",
  会员卡: "memberCard",
  积分卡: "pointsCard",
  优惠卡: "couponCard",
  折扣卡: "discountCard",
  权益卡: "benefitCard",
  年卡: "annual",
  季卡: "quarterly",
  月卡: "monthly",
  周卡: "weekly",
  日卡: "daily",
  次卡: "times",
  终身卡: "lifetime",
  永久卡: "perpetual",
  体验卡: "trialCard",
  试用卡: "trialCard",
  充值卡: "rechargeCard",
  消费卡: "consumeCard",
  通用卡: "universal",
  主题卡: "themed",
  联名卡: "coBrand",
  联名信用卡: "coBrand",
  定制卡: "custom",
  商务卡: "business",
  商务信用卡: "business",
  公务卡: "official",
  公务信用卡: "official",
  私务卡: "private",
  个人卡: "personal",
  家庭卡: "family",
  主卡: "primary",
  主卡人: "primary",
  副卡: "secondary",
  副卡人: "secondary",
  附属卡: "secondary",
  附卡: "secondary",
  附卡人: "secondary",
  持卡人: "cardHolder",
  开卡人: "cardHolder",
  发卡行: "issuer",
  发卡: "issue",
  发卡人: "issuer",
  发卡机构: "issuer",
  收单: "acquire",
  收单机构: "acquirer",
  收单行: "acquirer",
  清算: "clear",
  清算机构: "clearing",
  清分: "clear",
  调拨: "transfer",
  调拨单: "transferOrder",
  调拨人: "transferor",
  调入: "transferIn",
  调出: "transferOut",
  转出: "transferOut",
  转入: "transferIn",
  过户: "transfer",
  过户费: "transferFee",
};

export default dict;
