/**
 * 业务通用后缀（记录、列表、详情、管理、报告等）
 *
 * 自动拆分自原 dictBusiness.ts（2026-06-25）
 * 同 key 重复会 TS 编译报错，修改时请先确认该字未在其它分区登记。
 */
const dict: Record<string, string> = {
  // ============ 业务后缀 ============
  业务: "biz",
  业务流程: "bizFlow",
  业务规则: "bizRule",
  业务逻辑: "bizLogic",
  业务对象: "bizObject",
  业务模型: "bizModel",
  业务层: "bizLayer",
  业务域: "bizDomain",
  业务线: "bizLine",
  业务部门: "bizDept",
  业务部: "bizDept",
  业务方: "bizParty",
  业务端: "bizSide",
  业务前台: "bizFront",
  业务后台: "bizBack",
  业务中台: "bizMid",
  业务系统: "bizSys",
  业务平台: "bizPlatform",
  业务中心: "bizCenter",
  业务网关: "bizGw",
  业务接口: "bizApi",
  业务服务: "bizService",
  业务组件: "bizComp",
  业务模块: "bizModule",
  业务能力: "bizCap",
  业务引擎: "bizEngine",
  业务规则引擎: "ruleEngine",
  业务编排: "bizOrch",
  业务编排引擎: "orchEngine",
  业务编排平台: "orchPlatform",
  业务监控: "bizMonitor",
  业务告警: "bizAlert",
  业务报表: "bizReport",
  业务看板: "bizKanban",
  业务大屏: "bizScreen",
  业务指标: "bizKpi",
  业务考核: "bizAssess",
  业务绩效: "bizPerf",
  业务评估: "bizAssess",
  业务复盘: "bizRetro",
  业务总结: "bizSummary",
  业务规划: "bizPlan",
  业务计划: "bizPlan",
  业务策略: "bizStrategy",
  业务方案: "bizPlan",
  业务模式: "bizModel",
  业务架构: "bizArch",
  业务蓝图: "bizBlueprint",
  业务地图: "bizMap",
  业务画像: "bizPortrait",
  业务标签: "bizTag",
  业务属性: "bizAttr",
  业务码: "bizCode",
  业务编号: "bizNo",
  业务单号: "bizNo",
  业务流水: "bizSerial",
  业务状态: "bizStatus",
  业务类型: "bizType",
  业务分类: "bizCategory",
  业务渠道: "bizChannel",
  业务来源: "bizSource",
  业务场景: "bizScene",
  业务案例: "bizCase",
  业务模板: "bizTpl",
  业务配置: "bizConfig",
  业务参数: "bizParam",
  业务字典: "bizDict",
  业务码表: "bizDict",
  业务枚举: "bizEnum",
  业务常量: "bizConst",
  业务规则库: "ruleLib",
  业务规则集: "ruleSet",
  业务接口人: "bizOwner",
  业务负责人: "bizOwner",
  业务对接人: "bizContact",
  业务联系人: "bizContact",
  业务支持: "bizSupport",
  业务保障: "bizSupport",
  业务运营: "bizOps",
  业务分析: "bizAna",
  业务分析报告: "bizAnaReport",
  业务分析报表: "bizAnaReport",
  业务分析师: "bizAna",
  业务分析员: "bizAna",
  业务调研: "bizResearch",
  业务调研报告: "bizResearchReport",
  业务报告: "bizReport",
  业务日报: "bizDaily",
  业务周报: "bizWeekly",
  业务月报: "bizMonthly",
  业务季报: "bizQuarterly",
  业务年报: "bizAnnual",
};

export default dict;
