/**
 * 通用单字（消除 max-match 拆分后的单字兜底）
 *
 * 自动拆分自原 dictBusiness.ts（2026-06-25）
 * 同 key 重复会 TS 编译报错，修改时请先确认该字未在其它分区登记。
 */
const dict: Record<string, string> = {
  // ============ 通用单字（消除 max-match 拆分后单字兜底）============
  // 这里放各种词条拆分后剩下的高频单字。优先长词匹配，
  // 但被拆开后的"信息""架构""回调""字典""意见""帮助""红包"等单字
  // 也需要单字版兜底，避免兜底率被拉高。
  位: "slot",
  作: "act",
  信: "info",
  息: "info",
  架: "arch",
  构: "struct",
  回: "cb",
  调: "tune",
  业: "biz",
  药: "drug",
  品: "product",
  供: "supply",
  应: "apply",
  链: "chain",
  工: "work",
  流: "flow",
  程: "process",
  历: "history",
  红: "red",
  包: "pkg",
  字: "word",
  典: "dict",
  帮: "help",
  助: "assist",
  意: "idea",
  见: "view",

  // 长词组
  信息: "info",
  架构: "arch",
  回调: "cb",
  药品: "drug",
  供应链: "supplyChain",
  简历: "resume",
  红包: "redPkg",
  字典: "dict",
  帮助: "help",
  意见: "feedback",
  操作: "op",
  作业: "task",
  作家: "author",
  作品: "work",
  车位: "parkingSlot",
  用户位: "userSlot",
  位置: "pos",

  // 行业常见词
  营业: "business",
  营业额: "turnover",
  营收: "revenue",
  利润: "profit",
  亏损: "loss",
  余款: "balance",
  信用: "credit",
  信誉: "credit",
  信誉度: "reputation",
  信任: "trust",
  额度: "quota",
  授信: "creditGrant",
  借贷: "lend",
  贷款: "loan",
  逾期: "overdue",
  罚息: "penaltyInt",
  利息: "interest",
  本金: "principal",
  年化: "annualized",
  利率: "rate",
  汇率: "fxRate",
  汇款: "remit",
  开户: "openAcct",
  销户: "closeAcct",
  挂失: "reportLoss",
  补办: "reissue",
  激活: "activate",
  冻结: "freeze",
  解冻: "unfreeze",
  风险: "risk",
  合规: "compliance",
  审计: "audit",
  报税: "tax",
  申报: "declare",
  缴纳: "payTax",
  退税: "refundTax",
  开票: "invoice",
  冲红: "redRush",
  认证: "auth",
  实名: "realName",
  实名校验: "realNameChk",
  活体: "liveness",
  人脸: "face",
  指纹: "fingerprint",
  虹膜: "iris",
  声纹: "voiceprint",
  证件: "idDoc",
  身份证: "idCard",
  护照: "passport",
  驾照: "driverLic",
  营业执照: "bizLic",
  许可证: "license",
  备案: "filing",
  登记: "register",
  注册: "signup",
  注销: "logout",
  年检: "annualInsp",
  季检: "quarterly",
  月检: "monthly",
};

export default dict;
